version: '3'
services:
  consul1:
    image: consul:latest
    hostname: 'consul1'
    command: 'agent -server -bootstrap-expect 1 -client 0.0.0.0'
  consul2:
    image: consul:latest
    hostname: 'consul2'
    command: 'agent -join consul1 -client 0.0.0.0'
  consul3:
    image: consul:latest
    hostname: 'consul3'
    command: 'agent -join consul1 -client 0.0.0.0'
  node-a:
     build: ./
     environment:
       - 'CLUSTER_TYPE=consul'
       - 'CLUSTER_HOST=consul2'
       - 'CLUSTER_PORT=8500'
       - 'LIB=meshage'
       - 'SEED=consul1:8301'
       - 'DEBUG=meshage'
       - 'DELAY_STARTUP_MS=2000'
     volumes:
       - '../:/meshage:ro'
  node-b:
     build: ./
     environment:
       - 'CLUSTER_TYPE=consul'
       - 'CLUSTER_HOST=consul3'
       - 'CLUSTER_PORT=8500'
       - 'LIB=meshage'
       - 'SEED=consul1:8301'
       - 'DEBUG=meshage'
       - 'DELAY_STARTUP_MS=2000'
     volumes:
       - '../:/meshage:ro'