version: '3'
services:
  node-a:
    build: ./
    environment:
      - 'CLUSTER_HOST=node-a'
      - 'LIB=meshage'
      - 'DEBUG=meshage'
    volumes:
      - '../:/meshage:ro'
  node-b:
    build: ./
    environment:
      - 'CLUSTER_HOST=node-b'
      - 'LIB=meshage'
      - 'SEED=node-a:9473'
      - 'DEBUG=meshage'
    volumes:
      - '../:/meshage:ro'
  node-c:
      build: ./
      environment:
        - 'CLUSTER_HOST=node-c'
        - 'LIB=meshage'
        - 'SEED=node-a:9473'
        - 'DEBUG=meshage'
      volumes:
        - '../:/meshage:ro'
  node-d:
      build: ./
      environment:
        - 'CLUSTER_HOST=node-d'
        - 'LIB=meshage'
        - 'SEED=node-a:9473'
        - 'DEBUG=meshage'
      volumes:
        - '../:/meshage:ro'
  node-e:
      build: ./
      environment:
        - 'CLUSTER_HOST=node-e'
        - 'LIB=meshage'
        - 'SEED=node-a:9473'
        - 'DEBUG=meshage'
      volumes:
        - '../:/meshage:ro'