version: '2'
services:
  node-a:
    build: ./
    environment:
      - 'CLUSTER_HOST=node-a'
      - 'LIB=meshage'
      - 'DEBUG=none'
      - 'DELAY_STARTUP_MS=60000'
    volumes:
      - '../:/meshage:ro'
  node-b:
    build: ./
    environment:
      - 'CLUSTER_HOST=node-b'
      - 'LIB=meshage'
      - 'SEED=node-a:9473'
      - 'DEBUG=none'
    volumes:
      - '../:/meshage:ro'